/*
 * This file is generated by jOOQ.
 */
package ru.rzen.perflayground.jooq;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import ru.rzen.perflayground.jooq.tables.Messages;
import ru.rzen.perflayground.jooq.tables.Position;
import ru.rzen.perflayground.jooq.tables.Subdivision;
import ru.rzen.perflayground.jooq.tables.UserToPosition;
import ru.rzen.perflayground.jooq.tables.Users;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.messages</code>.
     */
    public final Messages MESSAGES = Messages.MESSAGES;

    /**
     * The table <code>public.position</code>.
     */
    public final Position POSITION = Position.POSITION;

    /**
     * The table <code>public.subdivision</code>.
     */
    public final Subdivision SUBDIVISION = Subdivision.SUBDIVISION;

    /**
     * The table <code>public.user_to_position</code>.
     */
    public final UserToPosition USER_TO_POSITION = UserToPosition.USER_TO_POSITION;

    /**
     * The table <code>public.users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Messages.MESSAGES,
            Position.POSITION,
            Subdivision.SUBDIVISION,
            UserToPosition.USER_TO_POSITION,
            Users.USERS
        );
    }
}
