/*
 * This file is generated by jOOQ.
 */
package ru.rzen.perflayground.jooq;


import ru.rzen.perflayground.jooq.tables.Messages;
import ru.rzen.perflayground.jooq.tables.Position;
import ru.rzen.perflayground.jooq.tables.Subdivision;
import ru.rzen.perflayground.jooq.tables.UserToPosition;
import ru.rzen.perflayground.jooq.tables.Users;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.messages</code>.
     */
    public static final Messages MESSAGES = Messages.MESSAGES;

    /**
     * The table <code>public.position</code>.
     */
    public static final Position POSITION = Position.POSITION;

    /**
     * The table <code>public.subdivision</code>.
     */
    public static final Subdivision SUBDIVISION = Subdivision.SUBDIVISION;

    /**
     * The table <code>public.user_to_position</code>.
     */
    public static final UserToPosition USER_TO_POSITION = UserToPosition.USER_TO_POSITION;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
