/*
 * This file is generated by jOOQ.
 */
package ru.rzen.perflayground.jooq.tables.pojos;


import java.io.Serializable;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Messages implements Serializable {

    private static final long serialVersionUID = 1L;

    private final UUID id;
    private final String body;

    public Messages(Messages value) {
        this.id = value.id;
        this.body = value.body;
    }

    public Messages(
        UUID id,
        String body
    ) {
        this.id = id;
        this.body = body;
    }

    /**
     * Getter for <code>public.messages.id</code>.
     */
    public UUID getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.messages.body</code>.
     */
    public String getBody() {
        return this.body;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Messages other = (Messages) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.body == null) {
            if (other.body != null)
                return false;
        }
        else if (!this.body.equals(other.body))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.body == null) ? 0 : this.body.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Messages (");

        sb.append(id);
        sb.append(", ").append(body);

        sb.append(")");
        return sb.toString();
    }
}
