/*
 * This file is generated by jOOQ.
 */
package ru.rzen.perflayground.jooq.tables.pojos;


import java.io.Serializable;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Position implements Serializable {

    private static final long serialVersionUID = 1L;

    private final UUID id;
    private final String name;
    private final String type;

    public Position(Position value) {
        this.id = value.id;
        this.name = value.name;
        this.type = value.type;
    }

    public Position(
        UUID id,
        String name,
        String type
    ) {
        this.id = id;
        this.name = name;
        this.type = type;
    }

    /**
     * Getter for <code>public.position.id</code>.
     */
    public UUID getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.position.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Getter for <code>public.position.type</code>.
     */
    public String getType() {
        return this.type;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Position other = (Position) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.type == null) {
            if (other.type != null)
                return false;
        }
        else if (!this.type.equals(other.type))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.type == null) ? 0 : this.type.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Position (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(type);

        sb.append(")");
        return sb.toString();
    }
}
