/*
 * This file is generated by jOOQ.
 */
package ru.rzen.perflayground.jooq.tables.pojos;


import java.io.Serializable;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserToPosition implements Serializable {

    private static final long serialVersionUID = 1L;

    private final UUID userId;
    private final UUID positionId;

    public UserToPosition(UserToPosition value) {
        this.userId = value.userId;
        this.positionId = value.positionId;
    }

    public UserToPosition(
        UUID userId,
        UUID positionId
    ) {
        this.userId = userId;
        this.positionId = positionId;
    }

    /**
     * Getter for <code>public.user_to_position.user_id</code>.
     */
    public UUID getUserId() {
        return this.userId;
    }

    /**
     * Getter for <code>public.user_to_position.position_id</code>.
     */
    public UUID getPositionId() {
        return this.positionId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final UserToPosition other = (UserToPosition) obj;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.positionId == null) {
            if (other.positionId != null)
                return false;
        }
        else if (!this.positionId.equals(other.positionId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.positionId == null) ? 0 : this.positionId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserToPosition (");

        sb.append(userId);
        sb.append(", ").append(positionId);

        sb.append(")");
        return sb.toString();
    }
}
