/*
 * This file is generated by jOOQ.
 */
package ru.rzen.perflayground.jooq.tables.pojos;


import java.io.Serializable;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Users implements Serializable {

    private static final long serialVersionUID = 1L;

    private final UUID id;
    private final UUID subdivisionId;
    private final String firstName;
    private final String lastName;
    private final String middleName;

    public Users(Users value) {
        this.id = value.id;
        this.subdivisionId = value.subdivisionId;
        this.firstName = value.firstName;
        this.lastName = value.lastName;
        this.middleName = value.middleName;
    }

    public Users(
        UUID id,
        UUID subdivisionId,
        String firstName,
        String lastName,
        String middleName
    ) {
        this.id = id;
        this.subdivisionId = subdivisionId;
        this.firstName = firstName;
        this.lastName = lastName;
        this.middleName = middleName;
    }

    /**
     * Getter for <code>public.users.id</code>.
     */
    public UUID getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.users.subdivision_id</code>.
     */
    public UUID getSubdivisionId() {
        return this.subdivisionId;
    }

    /**
     * Getter for <code>public.users.first_name</code>.
     */
    public String getFirstName() {
        return this.firstName;
    }

    /**
     * Getter for <code>public.users.last_name</code>.
     */
    public String getLastName() {
        return this.lastName;
    }

    /**
     * Getter for <code>public.users.middle_name</code>.
     */
    public String getMiddleName() {
        return this.middleName;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Users other = (Users) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.subdivisionId == null) {
            if (other.subdivisionId != null)
                return false;
        }
        else if (!this.subdivisionId.equals(other.subdivisionId))
            return false;
        if (this.firstName == null) {
            if (other.firstName != null)
                return false;
        }
        else if (!this.firstName.equals(other.firstName))
            return false;
        if (this.lastName == null) {
            if (other.lastName != null)
                return false;
        }
        else if (!this.lastName.equals(other.lastName))
            return false;
        if (this.middleName == null) {
            if (other.middleName != null)
                return false;
        }
        else if (!this.middleName.equals(other.middleName))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.subdivisionId == null) ? 0 : this.subdivisionId.hashCode());
        result = prime * result + ((this.firstName == null) ? 0 : this.firstName.hashCode());
        result = prime * result + ((this.lastName == null) ? 0 : this.lastName.hashCode());
        result = prime * result + ((this.middleName == null) ? 0 : this.middleName.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Users (");

        sb.append(id);
        sb.append(", ").append(subdivisionId);
        sb.append(", ").append(firstName);
        sb.append(", ").append(lastName);
        sb.append(", ").append(middleName);

        sb.append(")");
        return sb.toString();
    }
}
