/*
 * This file is generated by jOOQ.
 */
package ru.rzen.perflayground.jooq.tables.records;


import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import ru.rzen.perflayground.jooq.tables.Position;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PositionRecord extends UpdatableRecordImpl<PositionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.position.id</code>.
     */
    public PositionRecord setId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.position.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.position.name</code>.
     */
    public PositionRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.position.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.position.type</code>.
     */
    public PositionRecord setType(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.position.type</code>.
     */
    public String getType() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PositionRecord
     */
    public PositionRecord() {
        super(Position.POSITION);
    }

    /**
     * Create a detached, initialised PositionRecord
     */
    public PositionRecord(UUID id, String name, String type) {
        super(Position.POSITION);

        setId(id);
        setName(name);
        setType(type);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised PositionRecord
     */
    public PositionRecord(ru.rzen.perflayground.jooq.tables.pojos.Position value) {
        super(Position.POSITION);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setType(value.getType());
            resetChangedOnNotNull();
        }
    }
}
