/*
 * This file is generated by jOOQ.
 */
package ru.rzen.perflayground.jooq.tables.records;


import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import ru.rzen.perflayground.jooq.tables.Subdivision;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SubdivisionRecord extends UpdatableRecordImpl<SubdivisionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.subdivision.id</code>.
     */
    public SubdivisionRecord setId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.subdivision.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.subdivision.short_name</code>.
     */
    public SubdivisionRecord setShortName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.subdivision.short_name</code>.
     */
    public String getShortName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.subdivision.path</code>.
     */
    public SubdivisionRecord setPath(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.subdivision.path</code>.
     */
    public String getPath() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.subdivision.parent_id</code>.
     */
    public SubdivisionRecord setParentId(UUID value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.subdivision.parent_id</code>.
     */
    public UUID getParentId() {
        return (UUID) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SubdivisionRecord
     */
    public SubdivisionRecord() {
        super(Subdivision.SUBDIVISION);
    }

    /**
     * Create a detached, initialised SubdivisionRecord
     */
    public SubdivisionRecord(UUID id, String shortName, String path, UUID parentId) {
        super(Subdivision.SUBDIVISION);

        setId(id);
        setShortName(shortName);
        setPath(path);
        setParentId(parentId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised SubdivisionRecord
     */
    public SubdivisionRecord(ru.rzen.perflayground.jooq.tables.pojos.Subdivision value) {
        super(Subdivision.SUBDIVISION);

        if (value != null) {
            setId(value.getId());
            setShortName(value.getShortName());
            setPath(value.getPath());
            setParentId(value.getParentId());
            resetChangedOnNotNull();
        }
    }
}
