/*
 * This file is generated by jOOQ.
 */
package ru.rzen.perflayground.jooq.tables.records;


import java.util.UUID;

import org.jooq.impl.TableRecordImpl;

import ru.rzen.perflayground.jooq.tables.UserToPosition;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserToPositionRecord extends TableRecordImpl<UserToPositionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.user_to_position.user_id</code>.
     */
    public UserToPositionRecord setUserId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.user_to_position.user_id</code>.
     */
    public UUID getUserId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.user_to_position.position_id</code>.
     */
    public UserToPositionRecord setPositionId(UUID value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.user_to_position.position_id</code>.
     */
    public UUID getPositionId() {
        return (UUID) get(1);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserToPositionRecord
     */
    public UserToPositionRecord() {
        super(UserToPosition.USER_TO_POSITION);
    }

    /**
     * Create a detached, initialised UserToPositionRecord
     */
    public UserToPositionRecord(UUID userId, UUID positionId) {
        super(UserToPosition.USER_TO_POSITION);

        setUserId(userId);
        setPositionId(positionId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised UserToPositionRecord
     */
    public UserToPositionRecord(ru.rzen.perflayground.jooq.tables.pojos.UserToPosition value) {
        super(UserToPosition.USER_TO_POSITION);

        if (value != null) {
            setUserId(value.getUserId());
            setPositionId(value.getPositionId());
            resetChangedOnNotNull();
        }
    }
}
