/*
 * This file is generated by jOOQ.
 */
package ru.rzen.perflayground.jooq.tables.records;


import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import ru.rzen.perflayground.jooq.tables.Users;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UsersRecord extends UpdatableRecordImpl<UsersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.users.id</code>.
     */
    public UsersRecord setId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.users.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.users.subdivision_id</code>.
     */
    public UsersRecord setSubdivisionId(UUID value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.users.subdivision_id</code>.
     */
    public UUID getSubdivisionId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.users.first_name</code>.
     */
    public UsersRecord setFirstName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.users.first_name</code>.
     */
    public String getFirstName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.users.last_name</code>.
     */
    public UsersRecord setLastName(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.users.last_name</code>.
     */
    public String getLastName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.users.middle_name</code>.
     */
    public UsersRecord setMiddleName(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.users.middle_name</code>.
     */
    public String getMiddleName() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsersRecord
     */
    public UsersRecord() {
        super(Users.USERS);
    }

    /**
     * Create a detached, initialised UsersRecord
     */
    public UsersRecord(UUID id, UUID subdivisionId, String firstName, String lastName, String middleName) {
        super(Users.USERS);

        setId(id);
        setSubdivisionId(subdivisionId);
        setFirstName(firstName);
        setLastName(lastName);
        setMiddleName(middleName);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised UsersRecord
     */
    public UsersRecord(ru.rzen.perflayground.jooq.tables.pojos.Users value) {
        super(Users.USERS);

        if (value != null) {
            setId(value.getId());
            setSubdivisionId(value.getSubdivisionId());
            setFirstName(value.getFirstName());
            setLastName(value.getLastName());
            setMiddleName(value.getMiddleName());
            resetChangedOnNotNull();
        }
    }
}
